### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by iscas-zac** [EmNudge/watlings#10]
The readme doesn't mention that, but the `npm run` things use `bash` under the hood, and that is not supported in Windows. If Windows supported is not intended, it should be explicit especially when VSCode is mentioned.

**Comment by EmNudge** [comment]
Good call-out! I don't have a windows computer, but I'll get started porting the bash scripts over to node and see if I can get a PR out by EOD. I'm currently at Wasmcon, so it may take longer than I'd like

**Comment by EmNudge** [comment]
Let me know if there are still issues on windows for now. I've migrated the bash scripts to node, but I don't have a windows machine of my own right now to verify there aren't any other issues.

**Comment by iscas-zac** [comment]
Hi, thanks for responding! I tried the patch, but the problem with `npm start 001_hello` and `npm run test` in [JeffersGlass's comment](https://github.com/EmNudge/watlings/pull/11#issuecomment-1709101722) appeared. I have no idea about the reason currently.

**Comment by iscas-zac** [comment]
I'm not sure why the `spawn` behaves erroneously on Windows, and I changed it a little.

Also, according to https://github.com/nodejs/node/issues/37845, the filePath is to be acquired by `fileURLToPath`. I changed `getWastParser.mjs` like,
```js
...

      var path = new URL(filePath, import.meta.url).pathname;
      const fileName = path.match(/\/([^\/]+)\.wat$/)[1];
      const wasmPath = fileURLToPath(new URL(`../../.cache/${fileName}.wasm`, import.meta.url))
      path = fileURLToPath(new URL(filePath, import.meta.url))
      
      
      return new Promise((res, rej) => {
        spawn('node', ['node_modules/wabt/bin/wat2wasm', path, '-o', wasmPath], { stdio:'inherit' })

...
```
, and it compiles 001 successfully. Note that there are backslashes after `fileURLToPath` on Windows, and I don't want to change the regex part, so I keep the first pathname.

**Comment by EmNudge** [comment]
Thanks for the comment! Has the latest commit fixed the issues?

**Comment by iscas-zac** [comment]
Seems good. It compiles after `npm run solve 001_hello` and the two tests passed. I have only looked at that puzzle for now, but I suppose others are also fine. (Probably GitHub Actions can help test out other cases on all platforms.)

I think providing a `npm run solve all` and catching the error during `npm run build` when some puzzles are not done will be better (or even the watch mode like rustlings), but that is out of the scope of this issue.

Thanks for your work!
